version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    reviewers:
      - 'owner'
    assignees:
      - 'owner'
    commit-message:
      prefix: 'deps'
      include: 'scope'
